version: '3.8'

services:
  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./snapshots:/directus/snapshots
    environment:
      KEY: 'directus-cms-docker-key'
      SECRET: 'directus-cms-docker-secret'
      
      # データベース設定
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'
      
      # 管理者アカウント
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'admin_password'
      
      # キャッシュ設定
      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'
      
      # 言語設定
      DEFAULT_LANGUAGE: 'ja'
      
      # ストレージ設定
      STORAGE_LOCATIONS: 'local'
      STORAGE_LOCAL_DRIVER: 'local'
      STORAGE_LOCAL_ROOT: '/directus/uploads'
      
      # APIと認証
      PUBLIC_URL: 'http://localhost:8055'
      API_TOKEN_EXPIRATION: '7d'
      
      # CORS設定（Next.jsフロントエンド用）
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'http://localhost:3000'
      CORS_METHODS: 'GET,POST,PATCH,DELETE'
      CORS_ALLOWED_HEADERS: 'Content-Type,Authorization'
      CORS_EXPOSED_HEADERS: 'Content-Range'
      CORS_CREDENTIALS: 'true'
      CORS_MAX_AGE: '86400'
      
      # パフォーマンスとデバッグ設定
      RATE_LIMITER_ENABLED: 'false'
      LOG_LEVEL: 'info'
    depends_on:
      - database
      - cache
    restart: unless-stopped

  database:
    image: postgres:15
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'
    ports:
      - "5432:5432"
    restart: unless-stopped

  cache:
    image: redis:7
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
      
  # Next.jsフロントエンド
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_DIRECTUS_URL=http://localhost:8055
    depends_on:
      - directus
    restart: unless-stopped

volumes:
  directus-uploads:
  directus-extensions:
  database-data:
  redis-data: